name: my_tune_admin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_sidemenu: ^0.4.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  image_picker_web: ^3.0.0+1
  filesize: ^2.0.1
  fluttertoast: ^8.2.2
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  cloud_firestore: ^4.8.2
  http: ^0.13.5
  firebase_messaging: ^14.6.4
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  build_runner: ^2.4.6
  numeral: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.0
flutter:
  uses-material-design: true
